/**
 * Service Worker registration with Push notification support
 * This file registers the Vite PWA service worker and adds push event handlers
 */

if ('serviceWorker' in navigator) {
  window.addEventListener('load', async () => {
    try {
      // Register the service worker generated by Vite PWA
      const registration = await navigator.serviceWorker.register('/sw.js', {
        scope: '/'
      });

      console.log('✅ Service Worker registered:', registration.scope);

      // Wait for the service worker to be ready
      await navigator.serviceWorker.ready;

      // Add message listener for push events
      navigator.serviceWorker.addEventListener('message', (event) => {
        if (event.data && event.data.type === 'PUSH_NOTIFICATION') {
          console.log('📬 Push notification received:', event.data.payload);
        }
      });

      console.log('✅ Push notification listeners ready');
    } catch (error) {
      console.error('❌ Service Worker registration failed:', error);
    }
  });
}

// Handle push events (this will be picked up by the SW)
self.addEventListener?.('push', (event) => {
  const data = event.data?.json() ?? {};
  const title = data.title || 'MAFIS Notification';
  const options = {
    body: data.body || data.message || 'Nueva notificación',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    vibrate: [200, 100, 200],
    data: data
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

// Handle notification clicks
self.addEventListener?.('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(
    clients.openWindow('/')
  );
});
