"""Add notification preferences to users

Revision ID: bc011173c491
Revises: da5a1d2259d0
Create Date: 2025-11-28 13:44:46.891131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc011173c491'
down_revision = 'da5a1d2259d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_whatsapp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_push', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_push')
        batch_op.drop_column('notify_whatsapp')
        batch_op.drop_column('notify_email')

    # ### end Alembic commands ###
